source = ../src/ark_Vector.c ../src/ark_Array.c ../src/ark_memory.c ../src/ark_log.c ../src/ark_Queue.c
source += ../src/ark_Gapbuffer.c ../src/ark_Stack.c ../src/ark_Hashmap.c

file = ark_Array_test

# gcc ./ark_log_test.c -o ark_log_test.exe $(source)
# gcc ./ark_memory_test.c -o ark_memory_test.exe $(source)
# gcc ./ark_Vector_test.c -o ark_algorithm_test.exe $(source)

run : 
	gcc $(file).c -o $(file).exe $(source)