source = ../src/ark_Vector.c ../src/ark_memory.c ../src/ark_log.c ../src/ark_Queue.c ../src/ark_Gapbuffer.c ../src/ark_Stack.c ../src/ark_Array.c

# ark_log_test.c -> passed all test (multi threading can be implemented)

# gcc ./ark_Array_test.c -o ark_algorithm_test.exe $(source)

run : 
	gcc ./ark_log_test.c -o ark_log_test.exe $(source)
	gcc ./ark_memory_test.c -o ark_memory_test.exe $(source)
	gcc ./ark_Vector_test.c -o ark_algorithm_test.exe $(source)